### Health Check
GET http://localhost:3000/health

### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "password123",
  "profile": "https://example.com/test.jpg",
  "bio": "Test User Bio",
  "role": "user"
}

### Login with Admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}

### Login with Editor
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "editor@example.com",
  "password": "editor123"
}

### Login with User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "user123"
}

### Get Profile (replace TOKEN with actual token)
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0MjY5OTkwLCJleHAiOjE3NTQyNzA4OTB9.Aa3pgpe38xqyHRK4kmTpi_pHB_AFK1ZWYpResFPI85g

### Verify Token (replace TOKEN with actual token)
GET http://localhost:3000/api/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzUzOTMxMDc4LCJleHAiOjE3NTM5MzE5Nzh9.1itCP4LeOTHnnIF_H6m-GaBLZ0P_WQfSjRvS9Rip_Ig

### Refresh Token (replace REFRESH_TOKEN with actual refresh token)
POST http://localhost:3000/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "REFRESH_TOKEN"
}

### Logout (replace TOKEN with actual token)
POST http://localhost:3000/api/auth/logout
Authorization: Bearer TOKEN

### Logout with Refresh Token (replace TOKEN and REFRESH_TOKEN with actual tokens)
POST http://localhost:3000/api/auth/logout
Authorization: Bearer TOKEN
Content-Type: application/json

{
  "refreshToken": "REFRESH_TOKEN"
}

### Logout from All Devices (replace TOKEN with actual token)
POST http://localhost:3000/api/auth/logout-all
Authorization: Bearer TOKEN

### Get User's Active Tokens (replace TOKEN with actual token)
GET http://localhost:3000/api/auth/tokens
Authorization: Bearer 

### Edit contact information
PUT http://localhost:3000/api/contact-information
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0MjIwNTE0LCJleHAiOjE3NTQyMjE0MTR9.9Y8cZ9y2ca-rLD_PrXCD-cqSgeafF2ZEAbJ0UuCAh1A
Content-Type: application/json

{
  "email": "codecraf2t1@gmail.com",
  "phoneNumber": "082212131153118",
  "ourOffice": "Bogor12 kota"
}

### Update your profile
PUT http://localhost:3000/api/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0MjY5OTkwLCJleHAiOjE3NTQyNzA4OTB9.Aa3pgpe38xqyHRK4kmTpi_pHB_AFK1ZWYpResFPI85g
Content-Type: application/json

{
  "name": "Regular user updated",
  "email": "user@example.com",
  "bio": "Regular user updated bio"
}

### Delete your profile
DELETE http://localhost:3000/api/profile/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0MjY5OTkwLCJleHAiOjE3NTQyNzA4OTB9.Aa3pgpe38xqyHRK4kmTpi_pHB_AFK1ZWYpResFPI85g
Content-Type: application/json

### Get all permissions
GET http://localhost:3000/api/permission
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTQyNzg2ODUsImV4cCI6MTc1NDI3OTU4NX0.oS_lYbQMuEiEiG4TfbiKzRbYsjZ4dWZchFGkXogBtp8
Content-Type: application/json
